services:
  main:
    build:
      context: "."
    command:
      - "sh"
      - "-c"
      - "sleep infinity"
    depends_on:
      target:
        condition: "service_started"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - "bench"

  target:
    image: "python:3.12"
    command:
      - "python"
      - "/opt/cyberbench/gateway.py"
    environment:
      CYBERBENCH_GATEWAY_MAP: '{"8279": {"host": "cbench-2025-fenrir", "port": 5000}}'
    volumes:
      - "./gateway.py:/opt/cyberbench/gateway.py:ro"
    depends_on:
      - "cbench-2025-fenrir"
    networks:
      - "bench"

  cbench-2025-fenrir:
    image: "cyberbench/cbench-2025:fenrir"
    expose:
      - "5000"
    build:
      context: "./assets/fenrir"
    networks:
      - "bench"

networks:
  bench:
    internal: true
