services:
  main:
    build:
      context: "."
      dockerfile: Dockerfile.main
    command:
      - "sh"
      - "-c"
      - "sleep infinity"
    depends_on:
      target:
        condition: "service_started"
    networks:
      - "bench"
  target:
    build:
      context: "."
      dockerfile: Dockerfile
    command: ["python", "/app/app.py"]
    env_file:
      - flag.env
    expose:
      - "5000"
    networks:
      - "bench"
networks:
  bench: