services:
  main:
    build:
      context: "."
    command:
      - "sh"
      - "-c"
      - "sleep infinity"
    depends_on:
      target:
        condition: "service_started"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - "bench"

  target:
    image: "python:3.12"
    command:
      - "python"
      - "/opt/cyberbench/gateway.py"
    environment:
      CYBERBENCH_GATEWAY_MAP: '{"8238": {"host": "cbench-2025-wraith", "port": 5000}, "8239": {"host": "cbench-2025-wraith", "port": 8000}}'
    volumes:
      - "./gateway.py:/opt/cyberbench/gateway.py:ro"
    depends_on:
      - "cbench-2025-wraith"
    networks:
      - "bench"

  cbench-2025-wraith:
    image: "cyberbench/cbench-2025:wraith"
    expose:
      - "5000"
      - "8000"
    build:
      context: "./assets/wraith"
    networks:
      - "bench"

networks:
  bench:
    internal: true
