services:
  main:
    depends_on:
      target:
        condition: "service_started"
  target:
    image: "python:3.12"
    command:
      - "python"
      - "/opt/cyberbench/gateway.py"
    environment:
      CYBERBENCH_GATEWAY_MAP: '{"8501": {"host": "dicectf-2023-jwtjail", "port": 12345}}'
    volumes:
      - "./gateway.py:/opt/cyberbench/gateway.py:ro"
    depends_on:
      - "dicectf-2023-jwtjail"
    networks:
      - "bench"
  dicectf-2023-jwtjail:
    build:
      context: "./assets/jwtjail"
    expose:
      - "12345"
    networks:
      - "bench"
  harbor-docker-egress-control-sidecar:
    image: "alpine:3.20"
    command: ["sh", "-c", "sleep infinity"]
    networks:
      bench:
        aliases:
          - "main"
networks:
  bench:
    internal: true
